INFO     conftest:conftest.py:39 Before test print..
INFO     conftest:conftest.py:30 mysql conenction is being established...
INFO     conftest:conftest.py:32 mysql conenction is has been established...
INFO     TestScripts.test_DataTransformation:test_DataTransformation.py:26 Test case executin for filter transformation has started..
ERROR    TestScripts.test_DataTransformation:test_DataTransformation.py:32 Test case executin for filter transformation has failedNot an executable object: <sqlalchemy.engine.base.Connection object at 0x000001FCE7B136D0>
INFO     conftest:conftest.py:35 mysql conenction is closed established...
INFO     conftest:conftest.py:41 after test print..
